### ISSUE TITLE
 Missing describe block

### ISSUE THREAD

**Issue by monolithed** [webdriverio/wdio-dot-reporter#1]
Actual:

![img-2016-06-23-01-55-27](https://cloud.githubusercontent.com/assets/803674/16286523/a9e14db2-38e5-11e6-84ef-5ae5f207c9e5.png)
![img-2016-06-23-01-54-40](https://cloud.githubusercontent.com/assets/803674/16286524/a9e30dbe-38e5-11e6-9c39-fe5debfa882e.png)

Expected something like:

![reporter-spec-fail](https://cloud.githubusercontent.com/assets/803674/16537465/9c454cf8-400b-11e6-946e-fbf84c3b0512.png)

**Comment by dheerajbhaskar** [comment]
@monolithed I think this is the expected behavior from `dot` reporter. What you (and I) are looking for is the `spec` reporter [wdio spec reporter](https://github.com/webdriverio/wdio-spec-reporter).

I myself am trying to just fork dot reporter and the describe functionality.

I'm planning to base it on https://gist.github.com/jurgob/c86920043f0a7c766b79eb63562e15fe

You can use that in the meanwhile to provide spec like reporting. Instructions to use: https://github.com/webdriverio/webdriverio/issues/1129#issuecomment-203322469

**Comment by niksy** [comment]
@dheerajbhaskar any timeline on that fork you’re planning to release? It seems like there is no actual activity on main spec reporter repo and it will be nice to actually have one for those who want standard spec output.

**Comment by christian-bromann** [comment]
@niksy @dheerajbhaskar instead of releasing it, why not just contributing to the existing one?

**Comment by christian-bromann** [comment]
@monolithed this failure report is generated by webdriverio not this dot reporter. Change should be made there and a PR was already opened and merged (just not yet released).

**Comment by niksy** [comment]
@christian-bromann that is great and correct approach, but judging from that issue, it seems like there isn’t any proper activity for release (or I’m missing something) :/

**Comment by christian-bromann** [comment]
> it seems like there isn’t any proper activity for release

if someone comes up with a proper PR I would be happy to merge and release it.
